# Actually workflow name
name: build-and-lint

#triggers:define when this workflow should run
#trigger on push to these branches
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

#define a job(multiple jobs also)
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Lint backend
        working-directory: backend
        run: npm run lint -- --max-warnings=0

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint -- --max-warnings=0

      - name: Build backend image
        run: docker build -t backend ./backend

      - name: Build frontend image
        run: docker build -t frontend ./frontend

        #CD
  # deploy:
  # needs: build-and-lintif: github.event_name == 'push'
  # runs-on: ubuntu-latest

  # steps:
  #   - name: Checkout (optional)
  #     uses: actions/checkout@v4

  #   - name: Write SSH key
  #     run: |
  #       echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
  #       chmod 600 ec2_key.pem

  #   - name: Add EC2 host to known_hosts
  #     run: |
  #       mkdir -p ~/.ssh
  #       ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

  #   - name: Deploy on EC2
  #     env:
  #       EC2_HOST: ${{ secrets.EC2_HOST }}
  #       EC2_USER: ${{ secrets.EC2_USER }}
  #       EC2_APP_DIR: ${{ secrets.EC2_APP_DIR }}
  #     run: |
  #       ssh -i ec2_key.pem ${EC2_USER}@${EC2_HOST} << EOF
  #         set -e
  #         cd "${EC2_APP_DIR}"
  #         git fetch --all
  #         git reset --hard origin/main
  #         docker compose up -d --build
  #       EOF
